### ISSUE TITLE
Definition of target-related feature sets  might not be fully correct

### ISSUE THREAD

**Issue by Jakob-Bach** [CemOezcan/metalfi#29]
Currently, two of the meta-feature sets are defined by the following two lines of code in `metamodel.py`:

```
[x for x in train.columns if x.startswith("target")],
[x for x in train.columns if not x.startswith("target")]]
```

I don't know if this has the intended effect, though, as some of the meta-features from `pymfe` are also target-related without having "target" in their name.

**Comment by CemOezcan** [comment]
Meta-features, whose names start with `"target"`, are meant to be the importance-landmarking meta-features. I will rename those to `"Landmarking"`.

**Comment by Jakob-Bach** [comment]
Although the definition of meta-feature sets has changed, there are still some inconsistencies. For example, mutual information is considered univariate, though it is related to the target. Thus, it might be a good idea to go through the list of `pymfe` features and find out which are not univariate.

Plus, there is one interesting category which could be added: "univariate + bivariate" (as an intermediate step between univariate and all feature meta-features).

**Comment by CemOezcan** [comment]
Mutual information was in the wrong category. It has since been changed to "target_mut_inf".
