### ISSUE TITLE
Desribe how to reproduce results

### ISSUE THREAD

**Issue by Jakob-Bach** [CemOezcan/metalfi#46]
This means: which scripts have to be run (in which order, with which parameters if applicable) to reproduce the experiments and all plots.

**Comment by Jakob-Bach** [comment]
Installing all required packages from `requirements.txt` currently fails, as the specified `pymfe` version cannot be found (any more).

**Comment by CemOezcan** [comment]
I changed the `requirements.txt` file so that the available version of `pymfe` (currently 0.4) is installed. I additionally added the `sklearn-posthocs` package to the `requirements.txt` file.
